</main>

<footer>
    <small>&copy; <?= date("Y") ?> - Thijs Nissen Muziekproducties</small>
</footer>

<a href="#top-of-page" class="up">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15 11.25l-3-3m0 0l-3 3m3-3v7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
</a>

<!-- js -->
<script src="/js/lite-yt-embed.js"></script>
<script src="/js/main.js" type="module"></script>
<!-- end js -->

</body>
</html>
