<html lang="nl">
<head>
    <meta name="viewport" content="width=device-width initial-scale=1.0">

    <title>Thijs Nissen &bull; (Jazz)saxofonist, componist, bandleider en organisator</title>

    <meta name="description" content="(Jazz)saxofonist, componist, bandleider en organisator Thijs Nissen (Venlo, 1991) is de drijvende kracht achter zijn Thijs Nissen Trio. Ook speelt Thijs regelmatig samen in verschillende bezettingen met vooraanstaande musici uit de Nederlandse jazzscene. " />
    <meta name="keywords" content="Thijs, Nissen, Trio, Muziekproducties, Jazz, Muziek, Evenementen" />
    <meta name="theme-color" content="#fdfdfd" media="(prefers-color-scheme: light)">
    <meta name="theme-color" content="#fdfdfd" media="(prefers-color-scheme: dark)">

    <meta property="og:title" content="Thijs Nissen &bull; (Jazz)saxofonist, componist, bandleider en organisator" />
    <meta property="og:description" content="(Jazz)saxofonist, componist, bandleider en organisator Thijs Nissen (Venlo, 1991) is de drijvende kracht achter zijn Thijs Nissen Trio. Ook speelt Thijs regelmatig samen in verschillende bezettingen met vooraanstaande musici uit de Nederlandse jazzscene. " />
    <meta property="og:url" content="<?= $url ?>/" />
    <meta property="og:image" content="<?= $url ?>/img/og-image.png" />
    <meta property="og:locale" content="nl_NL" />
    <meta property="og:type" content="website" />

    <link rel="icon" type="image/svg+xml" href="/img/favicon.svg">
    <link rel="icon" type="image/png" href="/img/favicon.png">

    <!-- css -->
    <link rel="stylesheet" href="/css/lite-yt-embed.css" />
    <link rel="stylesheet" href="/css/main.css" />
    <!-- end css -->
</head>
<body id="top-of-page">

<header>
    <img src="/img/thijs-nissen.png" alt="Thijs Nissen Muziekproducties">
</header>

<nav>
    <a href="#thijs-nissen">Thijs Nissen</a> &#8725; 
    <a href="#thijs-nissen-trio">Thijs Nissen Trio</a> &#8725; 
    <a href="#optredens">Optredens</a> &#8725; 
    <a href="#contact">Contact</a>
</nav>

<main>