<article id="thijs-nissen">
    <h1>Thijs Nissen</h1>
    <p>
        (Jazz)saxofonist, componist, bandleider en organisator Thijs Nissen (Venlo, 1991) is de drijvende kracht achter zijn Thijs Nissen Trio.  
        Ook speelt Thijs regelmatig samen in verschillende bezettingen met vooraanstaande musici uit de Nederlandse jazzscene. 
        Thijs studeerde aan het conservatorium van Rotterdam (Codarts).
    </p>

    <p>
        Zijn meest recente project is een ode aan de legendarische jazzpianist Horace Silver. 
        Een quintet dat de titel Goldstein & Silver draagt. De band presenteert een actuele kijk op de muziek uit de hoogtijdagen van de jazz.
    </p>

    <p>
        Daarnaast is Thijs actief als (concert)organisator en zet hij zich in voor de promotie van jazzmuziek via initiatieven zoals <a href="https://closertojazz.nl/">Closer to Jazz</a>, <a href="https://jazzinlimburg.nl/">Jazz in Limburg</a> en <a href="https://northsearoundtown.nl/">North Sea Round Town</a>.
    </p>

    <p>
        Thijs produceert de jazzpodcast <a href="https://dansenendeblues.nl/">Dansen en de blues</a>. De podcast biedt een digitaal podium aan de fine fleur van de Nederlandse jazzmuziek. 
        Diepgaande interviews geven een intiem inkijkje in de persoon achter de muziek. Dansen en de blues wordt ook uitgezonden op de <a href="https://www.concertzender.nl/">Concertzender</a>.
    </p>

    <p>
        Als adviseur en programmamaker is Thijs actief bij <a href="https://jwajazz.nl/">Stichting Jazz En Wereldmuziek Kollektief</a> in Den Haag en de <a href="https://jazzcentrale.nl/">Jazz Centrale</a> in Rotterdam.
    </p>

    <lite-youtube videoid="EwaySj4dSmY" params="controls=0&modestbranding=1&rel=0" class="video-container"></lite-youtube>
</article>