<article id="thijs-nissen-trio">
    <h1>Thijs Nissen Trio</h1>
    <p>
        Swing, ritme en melodie. Dat kunt je verwachten van het Thijs Nissen Trio. 
        Met een solide basis van keiharde swing, schuwt deze formatie zich echter ook niet voor een lyrische ballad. 
        Drie doorgewinterde musici met als overkoepelende factor het Great American Songbook, 
        waardoor zij zich telkens weer weten te laten inspireren tot het kiezen van nieuw en interessant repertoire.
    </p>
    
    <lite-youtube videoid="Iec3yBF9xj8" params="controls=0&modestbranding=1&rel=0" class="video-container"></lite-youtube>
</article>